"use strict";
exports.__esModule = true;
var shape_class_1 = require("./shape-class");
var circle_class_1 = require("./circle-class");
var rectangle_class_1 = require("./rectangle-class");
var square_class_1 = require("./square-class");
var shape = new shape_class_1.Shape('red', true);
console.log(shape);
console.log(shape.toString());
var circle = new circle_class_1.Circle('black', true, 3.0);
console.log(circle);
console.log(circle.getArea());
console.log(circle.getPerimeter());
console.log(circle.toString());
var rectangle = new rectangle_class_1.Rectangle('yellow', false, 10, 20);
console.log(rectangle);
console.log(rectangle.getArea());
console.log(rectangle.getPerimeter());
console.log(rectangle.toString());
var square = new square_class_1.Square('brown', true, 5);
console.log(square);
console.log(square.getArea());
console.log(square.getPerimeter());
console.log(square.toString());
